name: Publish Package

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2

    - name: Set up Dart
      uses: dart-lang/setup-dart@v1 

    - name: Publish to GitHub Packages
      run: flutter pub publish --server=https://pub.pkg.github.com/avoram/seven_module_1 --force
      env:
        PUB_TOKEN: ${{secrets.GHP_TOKEN}}
